services:
  car-store-oauth-mysql-server:
    container_name: car-store-oauth-mysql-server
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=oauth_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    networks:
      - store-network

  car-store-mysql-server:
    container_name: car-store-mysql-server
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=store_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"
    networks:
      - store-network

  car-store-oauth-server:
    container_name: car-store-oauth-server
    build:
      context: oauth-ms/
      no_cache: true
    environment:
      DB_HOST: car-store-oauth-mysql-server
      DB_PORT: 3306
      DB_NAME: oauth_db
      DB_USER: root
      DB_PASSWORD: root
      ISSUER_HOST: http://car-store-oauth-server
      ISSUER_PORT: 9001
    depends_on:
      - car-store-oauth-mysql-server
    ports:
      - "9001:9001"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    networks:
      - store-network

  car-store-ms-server:
    container_name: car-store-ms-server
    build:
      context: store-ms/
      no_cache: true
    environment:
      DB_HOST: car-store-mysql-server
      DB_PORT: 3307
      DB_NAME: store_db
      DB_USER: root
      DB_PASSWORD: root
      ISSUER_HOST: http://car-store-oauth-server
      ISSUER_PORT: 9001
    depends_on:
      - car-store-mysql-server
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    networks:
      - store-network

networks:
  store-network:
    driver: bridge
